# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

# Sutay's Academic Menu Configuration
main:
  - name: About
    url: /about/
    weight: 10
  - name: Computational Chemistry: what is it and what it is not...
    url: /computational-chemistry/
    weight: 20
  - name: Research
    url: /research/
    weight: 30
  - name: List of Publications
    url: /publications/
    weight: 40
  - name: Lab Members
    url: /members/
    weight: 50
  - name: Contact
    url: /contact/
    weight: 60

